### PR TITLE
Make displayed game name editable

### PR DESCRIPTION
**Pull request by Sven65**
Because it should be a feature.

### CODE REVIEW

**Comment by Snazzah** [comment]
What use would this make exactly?

**Comment by FichteFoll** [comment]
The small icon hover text doesn't have a correlation with the application/game run. Not directly, at least, so I don't see the point in this either.

**Comment by Sven65** [comment]
Oh, I changed the wrong thing, I was looking to change the name of the displayed game because I don't want it to just be "Sublime Text"

**Comment by FichteFoll** [comment]
This isn't possible with the API provided by Discord. It can only be changed globally for everyone using the same appid. See also https://github.com/erengy/taiga/issues/450#issuecomment-373199684.

**Comment by Sven65** [comment]
I see, thanks.

**Pull request closed without merging**
