### PR TITLE
Added Pascal

### PR DESCRIPTION
**Pull request by AdamBures**
Added pascal icon

### CODE REVIEW

**Comment by TorchedSammy** [comment]
this really should have been in 1 pull request instead of #79 and #78

**Comment by AdamBures** [comment]
> this really should have been in 1 pull request instead of #79 and #78

Yeah sorry about that I pulled it and forgot about the logo.

**Comment by Snazzah** [comment]
Is there a better quality icon available for this language?

**Comment by TorchedSammy** [comment]
it also doesnt quite fit in with the style of the other sites, i can make another one if wanted

**Comment by Snazzah** [comment]
If you could make a better one, that would be good.

**Comment by TorchedSammy** [comment]
windows doesnt want to boot and i can't really use gimp
could probably find a decent better resolution one at google images

**Comment by Snazzah** [comment]
I'll replace the icon.

**Pull request merged**
